### ISSUE TITLE
ROI window not focusable

### ISSUE THREAD

**Issue by Raphintosh** [PTRRupprecht/Drawing-ROIs-without-GUI#1]
The region of interest plot is not showing after running the codes as demonstrated in the video

**Comment by PTRRupprecht** [comment]
Any errors in Matlab?

If not, has the window maybe opened in the background or on a different (non-existent) screen?

Without any further information, it will be impossible to track the issue down.

**Comment by PTRRupprecht** [comment]
Probably the window opened in the background. This feature/bug was now fixed.
